namespace ONEVO.Agent.TrayApp.Services;

using ONEVO.Agent.TrayApp.ViewModels;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

public sealed record DailySummaryPdfData(
    string StatusText,
    string ClockInDisplay,
    string ClockOutDisplay,
    string TotalShiftDisplay,
    string WorkingTimeDisplay,
    string BreakTimeDisplay,
    string ProductiveTimeDisplay,
    string IdleTimeDisplay,
    string BreakSessionsDisplay,
    IReadOnlyList<TopAppItem> TopApps);

/// <summary>
/// Renders the same locally-known session summary shown on EndSessionPage as a one-page
/// PDF, entirely client-side — no backend call. The TrayApp only holds a device credential
/// with no HR permissions, so it cannot call the HR-facing daily-report export API; this
/// mirrors that endpoint's layout using data already loaded into the view model.
/// </summary>
public static class DailySummaryPdfBuilder
{
    public static byte[] Build(DailySummaryPdfData data)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(36);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text("OneXso WorkPulse").FontSize(18).Bold();
                    col.Item().Text("Daily Work Summary").FontSize(12).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(2).Text(DateTime.Now.ToString("dddd, d MMMM yyyy"))
                        .FontSize(10).FontColor(Colors.Grey.Medium);
                });

                page.Content().PaddingTop(16).Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Component(new SummaryTile("Status", data.StatusText));
                        row.RelativeItem().Component(new SummaryTile("Clock In", data.ClockInDisplay));
                        row.RelativeItem().Component(new SummaryTile("Clock Out", data.ClockOutDisplay));
                        row.RelativeItem().Component(new SummaryTile("Total Shift", data.TotalShiftDisplay));
                    });

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Component(new SummaryTile("Working Time", data.WorkingTimeDisplay));
                        row.RelativeItem().Component(new SummaryTile("Break Time", data.BreakTimeDisplay));
                        row.RelativeItem().Component(new SummaryTile("Break Sessions", data.BreakSessionsDisplay));
                    });

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Component(new SummaryTile("Productive Time", data.ProductiveTimeDisplay));
                        row.RelativeItem().Component(new SummaryTile("Idle Time", data.IdleTimeDisplay));
                        row.RelativeItem();
                    });

                    col.Item().PaddingTop(8).Text("Top Applications Used Today").FontSize(12).Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(HeaderCellStyle).Text("Application");
                            header.Cell().Element(HeaderCellStyle).AlignRight().Text("Duration");
                        });

                        var apps = data.TopApps.Count == 0
                            ? [new TopAppItem("No app activity yet", "00:00:00")]
                            : data.TopApps;

                        foreach (var app in apps)
                        {
                            table.Cell().Element(BodyCellStyle).Text(app.Name);
                            table.Cell().Element(BodyCellStyle).AlignRight().Text(app.Duration);
                        }

                        static IContainer HeaderCellStyle(IContainer c) =>
                            c.PaddingVertical(4).BorderBottom(1).BorderColor(Colors.Grey.Darken1);

                        static IContainer BodyCellStyle(IContainer c) =>
                            c.PaddingVertical(4).BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2);
                    });
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by OneXso WorkPulse on ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span(DateTime.Now.ToString("d MMM yyyy, h:mm tt")).FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }

    private sealed class SummaryTile(string label, string value) : IComponent
    {
        public void Compose(IContainer container)
        {
            container.Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(8).Column(col =>
            {
                col.Item().Text(label).FontSize(8).FontColor(Colors.Grey.Medium);
                col.Item().Text(value).FontSize(12).Bold();
            });
        }
    }
}
